// place_captions.jsx — generated by build_xmeml.py. Run it against Premiere with the sequence open and active.
// Premiere has no built-in "run script" menu in most builds; the reliable way is VS Code + Adobe's "ExtendScript
// Debugger" extension: open this file, pick "Adobe Premiere Pro" as the target, press Run. (If your build has
// File > Scripts > Run Script File, that works too.) See references/premiere-import.md.
// It places one editable Motion Graphics template clip per caption phrase and one for the hook blurb.
// Every clip stays a normal graphic you can restyle, retime or retype. Safe to re-run on a fresh sequence only
// (it does not delete earlier captions). Set DRY = true to log what it WOULD do without touching the sequence.
/*__DATA__*/
var DRY = false;
var TICKS = 254016000000;     // Premiere ticks per second
var log = [];
function say(s) { log.push(s); $.writeln(s); }

// Names of the template's exposed parameters (Essential Graphics panel). Rename here if yours differ.
var P_LINE = "Line";          // the caption text
var P_KEY  = "Keyword";       // the highlighted word (second text parameter)
var P_BLURB = "Text";         // the blurb template's single text parameter

function setParam(trackItem, name, value) {
    var comp = trackItem.getMGTComponent();
    if (!comp) { say("  ! no MGT component on clip"); return false; }
    for (var i = 0; i < comp.properties.numItems; i++) {
        var p = comp.properties[i];
        if (p.displayName == name) { p.setValue(value, true); return true; }
    }
    say("  ! parameter '" + name + "' not found (have: " + listParams(comp) + ")");
    return false;
}
function listParams(comp) { var o = []; for (var i = 0; i < comp.properties.numItems; i++) o.push(comp.properties[i].displayName); return o.join(", "); }

function place(seq, mogrtPath, start, end, track) {
    if (DRY) return {end: null, getMGTComponent: function () { return null; }};
    var ti = seq.importMGT(mogrtPath, String(Math.round(start * TICKS)), track, 0);
    if (!ti) return null;
    var t = new Time(); t.seconds = end; ti.end = t;
    return ti;
}

(function main() {
    var seq = app.project.activeSequence;
    if (!seq) { alert("Open the sequence first, then run this again."); return; }
    if (!File(DATA.mogrt).exists) { alert("Caption template not found:\n" + DATA.mogrt + "\n\nBuild it with references/mogrt-caption-template.md, or pass --mogrt <path> to build_xmeml.py."); return; }
    var n = 0, bad = 0;
    for (var i = 0; i < DATA.cues.length; i++) {
        var c = DATA.cues[i];                       // [start, end, text, keyword]
        var kw = c[3] || "";
        var ti = place(seq, DATA.mogrt, c[0], c[1], DATA.capTrack);
        if (!ti) { say("cue " + i + " failed: " + c[2]); bad++; continue; }
        if (!DRY) { setParam(ti, P_LINE, c[2]); setParam(ti, P_KEY, kw); }
        say((DRY ? "[dry] " : "") + "caption " + c[0].toFixed(2) + "-" + c[1].toFixed(2) + "  " + c[2] + (kw ? "   [" + kw + "]" : ""));
        n++;
    }
    if (DATA.blurb) {
        var bm = File(DATA.blurbMogrt).exists ? DATA.blurbMogrt : DATA.mogrt;
        var b = place(seq, bm, DATA.blurb[0], DATA.blurb[1], DATA.blurbTrack);
        if (b && !DRY) { if (bm == DATA.blurbMogrt) setParam(b, P_BLURB, DATA.blurb[2]); else { setParam(b, P_LINE, DATA.blurb[2]); setParam(b, P_KEY, ""); } }
        say((DRY ? "[dry] " : "") + "blurb " + DATA.blurb[2]);
    }
    alert("Placed " + n + " captions" + (bad ? " (" + bad + " failed — see the ExtendScript console)" : "") + ".");
})();
